// Mocks generated by Mockito 5.4.6 from annotations
// in pippo/test/_disabled/property/features/core/lesson/lesson_controller_property_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i8;

import 'package:cloud_firestore/cloud_firestore.dart' as _i3;
import 'package:get/get.dart' as _i2;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:pippo/features/inners/gamification/controllers/gamification_controller.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeRxBool_0 extends _i1.SmartFake implements _i2.RxBool {
  _FakeRxBool_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxString_1 extends _i1.SmartFake implements _i2.RxString {
  _FakeRxString_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxInt_2 extends _i1.SmartFake implements _i2.RxInt {
  _FakeRxInt_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFirebaseFirestore_3 extends _i1.SmartFake
    implements _i3.FirebaseFirestore {
  _FakeFirebaseFirestore_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_4<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_5 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GamificationController].
///
/// See the documentation for Mockito's code generation for more information.
class MockGamificationController extends _i1.Mock
    implements _i4.GamificationController {
  MockGamificationController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_0(this, Invocation.getter(#isLoading)),
          )
          as _i2.RxBool);

  @override
  _i2.RxString get errorMessage =>
      (super.noSuchMethod(
            Invocation.getter(#errorMessage),
            returnValue: _FakeRxString_1(
              this,
              Invocation.getter(#errorMessage),
            ),
          )
          as _i2.RxString);

  @override
  _i2.RxInt get currentStreak =>
      (super.noSuchMethod(
            Invocation.getter(#currentStreak),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#currentStreak)),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get longestStreak =>
      (super.noSuchMethod(
            Invocation.getter(#longestStreak),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#longestStreak)),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get currentEnergy =>
      (super.noSuchMethod(
            Invocation.getter(#currentEnergy),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#currentEnergy)),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get gems =>
      (super.noSuchMethod(
            Invocation.getter(#gems),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#gems)),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get totalXp =>
      (super.noSuchMethod(
            Invocation.getter(#totalXp),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#totalXp)),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get weeklyXP =>
      (super.noSuchMethod(
            Invocation.getter(#weeklyXP),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#weeklyXP)),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get todayXp =>
      (super.noSuchMethod(
            Invocation.getter(#todayXp),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#todayXp)),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get level =>
      (super.noSuchMethod(
            Invocation.getter(#level),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#level)),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get xpToNextLevel =>
      (super.noSuchMethod(
            Invocation.getter(#xpToNextLevel),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#xpToNextLevel)),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get totalGemsEarned =>
      (super.noSuchMethod(
            Invocation.getter(#totalGemsEarned),
            returnValue: _FakeRxInt_2(
              this,
              Invocation.getter(#totalGemsEarned),
            ),
          )
          as _i2.RxInt);

  @override
  _i2.RxInt get totalGemsSpent =>
      (super.noSuchMethod(
            Invocation.getter(#totalGemsSpent),
            returnValue: _FakeRxInt_2(this, Invocation.getter(#totalGemsSpent)),
          )
          as _i2.RxInt);

  @override
  _i2.RxString get currentLeague =>
      (super.noSuchMethod(
            Invocation.getter(#currentLeague),
            returnValue: _FakeRxString_1(
              this,
              Invocation.getter(#currentLeague),
            ),
          )
          as _i2.RxString);

  @override
  _i3.FirebaseFirestore get firestore =>
      (super.noSuchMethod(
            Invocation.getter(#firestore),
            returnValue: _FakeFirebaseFirestore_3(
              this,
              Invocation.getter(#firestore),
            ),
          )
          as _i3.FirebaseFirestore);

  @override
  bool get hasUnlimitedEnergy =>
      (super.noSuchMethod(
            Invocation.getter(#hasUnlimitedEnergy),
            returnValue: false,
          )
          as bool);

  @override
  bool get hasXpBooster =>
      (super.noSuchMethod(Invocation.getter(#hasXpBooster), returnValue: false)
          as bool);

  @override
  bool get hasGemMultiplier =>
      (super.noSuchMethod(
            Invocation.getter(#hasGemMultiplier),
            returnValue: false,
          )
          as bool);

  @override
  bool get streakFreezeAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#streakFreezeAvailable),
            returnValue: false,
          )
          as bool);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  String getXpBoosterTimeRemaining() =>
      (super.noSuchMethod(
            Invocation.method(#getXpBoosterTimeRemaining, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getXpBoosterTimeRemaining, []),
            ),
          )
          as String);

  @override
  String getGemMultiplierTimeRemaining() =>
      (super.noSuchMethod(
            Invocation.method(#getGemMultiplierTimeRemaining, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getGemMultiplierTimeRemaining, []),
            ),
          )
          as String);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> loadStats() =>
      (super.noSuchMethod(
            Invocation.method(#loadStats, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  bool canStartLesson() =>
      (super.noSuchMethod(
            Invocation.method(#canStartLesson, []),
            returnValue: false,
          )
          as bool);

  @override
  String getNextEnergyTime() =>
      (super.noSuchMethod(
            Invocation.method(#getNextEnergyTime, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getNextEnergyTime, []),
            ),
          )
          as String);

  @override
  _i6.Future<void> purchaseEnergyRefill() =>
      (super.noSuchMethod(
            Invocation.method(#purchaseEnergyRefill, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> purchaseStreakFreeze() =>
      (super.noSuchMethod(
            Invocation.method(#purchaseStreakFreeze, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> purchaseXpBooster() =>
      (super.noSuchMethod(
            Invocation.method(#purchaseXpBooster, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> purchaseGemMultiplier() =>
      (super.noSuchMethod(
            Invocation.method(#purchaseGemMultiplier, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<List<Map<String, dynamic>>> queryHistory({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryHistory, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> queryLessonHistory({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryLessonHistory, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> queryStreakMilestones({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryStreakMilestones, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<List<Map<String, dynamic>>> queryLevelUps({
    DateTime? startDate,
    DateTime? endDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#queryLevelUps, [], {
              #startDate: startDate,
              #endDate: endDate,
            }),
            returnValue: _i6.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i6.Future<List<Map<String, dynamic>>>);

  @override
  _i6.Future<void> onLessonStart() =>
      (super.noSuchMethod(
            Invocation.method(#onLessonStart, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> onLessonComplete(
    int? baseXp,
    int? baseGems,
    bool? isPerfect, {
    String? lessonId = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #onLessonComplete,
              [baseXp, baseGems, isPerfect],
              {#lessonId: lessonId},
            ),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void calculateEnergyRegenerationPublic() => super.noSuchMethod(
    Invocation.method(#calculateEnergyRegenerationPublic, []),
    returnValueForMissingStub: null,
  );

  @override
  void consumeEnergyPublic() => super.noSuchMethod(
    Invocation.method(#consumeEnergyPublic, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLastEnergyRegenAt(DateTime? date) => super.noSuchMethod(
    Invocation.method(#setLastEnergyRegenAt, [date]),
    returnValueForMissingStub: null,
  );

  @override
  void setUnlimitedEnergyUntil(DateTime? date) => super.noSuchMethod(
    Invocation.method(#setUnlimitedEnergyUntil, [date]),
    returnValueForMissingStub: null,
  );

  @override
  DateTime getLastEnergyRegenAt() =>
      (super.noSuchMethod(
            Invocation.method(#getLastEnergyRegenAt, []),
            returnValue: _FakeDateTime_5(
              this,
              Invocation.method(#getLastEnergyRegenAt, []),
            ),
          )
          as DateTime);

  @override
  void updateStreakPublic() => super.noSuchMethod(
    Invocation.method(#updateStreakPublic, []),
    returnValueForMissingStub: null,
  );

  @override
  void setLastStreakDate(String? date) => super.noSuchMethod(
    Invocation.method(#setLastStreakDate, [date]),
    returnValueForMissingStub: null,
  );

  @override
  String getLastStreakDate() =>
      (super.noSuchMethod(
            Invocation.method(#getLastStreakDate, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getLastStreakDate, []),
            ),
          )
          as String);

  @override
  void setStreakFreezeAvailable(bool? value) => super.noSuchMethod(
    Invocation.method(#setStreakFreezeAvailable, [value]),
    returnValueForMissingStub: null,
  );

  @override
  bool getStreakFreezeAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#getStreakFreezeAvailable, []),
            returnValue: false,
          )
          as bool);

  @override
  void setStreakFreezeUsedToday(bool? value) => super.noSuchMethod(
    Invocation.method(#setStreakFreezeUsedToday, [value]),
    returnValueForMissingStub: null,
  );

  @override
  bool getStreakFreezeUsedToday() =>
      (super.noSuchMethod(
            Invocation.method(#getStreakFreezeUsedToday, []),
            returnValue: false,
          )
          as bool);

  @override
  void checkStreakMilestonesPublic() => super.noSuchMethod(
    Invocation.method(#checkStreakMilestonesPublic, []),
    returnValueForMissingStub: null,
  );

  @override
  void setMilestonesReached(List<int>? milestones) => super.noSuchMethod(
    Invocation.method(#setMilestonesReached, [milestones]),
    returnValueForMissingStub: null,
  );

  @override
  List<int> getMilestonesReached() =>
      (super.noSuchMethod(
            Invocation.method(#getMilestonesReached, []),
            returnValue: <int>[],
          )
          as List<int>);

  @override
  void addXpPublic(int? baseXp) => super.noSuchMethod(
    Invocation.method(#addXpPublic, [baseXp]),
    returnValueForMissingStub: null,
  );

  @override
  void checkXpResetsPublic() => super.noSuchMethod(
    Invocation.method(#checkXpResetsPublic, []),
    returnValueForMissingStub: null,
  );

  @override
  void checkLevelUpPublic() => super.noSuchMethod(
    Invocation.method(#checkLevelUpPublic, []),
    returnValueForMissingStub: null,
  );

  @override
  bool isFirstLessonOfDayPublic() =>
      (super.noSuchMethod(
            Invocation.method(#isFirstLessonOfDayPublic, []),
            returnValue: false,
          )
          as bool);

  @override
  void setXpBoosterUntil(DateTime? date) => super.noSuchMethod(
    Invocation.method(#setXpBoosterUntil, [date]),
    returnValueForMissingStub: null,
  );

  @override
  void setLastWeeklyResetDate(String? date) => super.noSuchMethod(
    Invocation.method(#setLastWeeklyResetDate, [date]),
    returnValueForMissingStub: null,
  );

  @override
  String getLastWeeklyResetDate() =>
      (super.noSuchMethod(
            Invocation.method(#getLastWeeklyResetDate, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getLastWeeklyResetDate, []),
            ),
          )
          as String);

  @override
  void setLastDailyResetDate(String? date) => super.noSuchMethod(
    Invocation.method(#setLastDailyResetDate, [date]),
    returnValueForMissingStub: null,
  );

  @override
  String getLastDailyResetDate() =>
      (super.noSuchMethod(
            Invocation.method(#getLastDailyResetDate, []),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#getLastDailyResetDate, []),
            ),
          )
          as String);

  @override
  void setGemMultiplierUntil(DateTime? date) => super.noSuchMethod(
    Invocation.method(#setGemMultiplierUntil, [date]),
    returnValueForMissingStub: null,
  );

  @override
  String formatDateForStreakPublic(DateTime? date) =>
      (super.noSuchMethod(
            Invocation.method(#formatDateForStreakPublic, [date]),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.method(#formatDateForStreakPublic, [date]),
            ),
          )
          as String);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Disposer addListener(_i7.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i7.Disposer);

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i8.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Disposer addListenerId(Object? key, _i7.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i7.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}
